Extract function detail::register_run_policy to register policies
This fixes warnings generated by clang-tidy (errors in my case because I use the flag -warnings-as-errors):
=======
bandit/bandit/run_policies/run_policy.h:45:5: error: Returning null reference [clang-analyzer-core.uninitialized.UndefReturn,-warnings-as-errors]
    return *policy_;
    ^
bandit-main/main.cpp:15:9: note: Calling 'run'
        return bandit::run(argc, argv);
               ^
bandit/bandit/runner.h:97:5: note: Calling 'registered_run_policy'
    registered_run_policy(run_policy.get());
    ^
bandit/bandit/run_policies/run_policy.h:38:5: note: 'policy_' initialized to a null pointer value
    static struct run_policy* policy_;
    ^
bandit/bandit/run_policies/run_policy.h:40:8: note: Assuming 'policy' is null
    if(policy)
       ^
bandit/bandit/run_policies/run_policy.h:40:5: note: Taking false branch
    if(policy)
    ^
bandit/bandit/run_policies/run_policy.h:45:5: note: Returning null reference
    return *policy_;
    ^
=======