Extract function detail::register_listener to register listener
This fixes warnings generated by clang-tidy (errors in my case because I use the flag -warnings-as-errors):
=======
bandit/bandit/reporters/reporters.h:24:5: error: Returning null reference [clang-analyzer-core.uninitialized.UndefReturn,-warnings-as-errors]
    return *reporter_;
    ^
bandit-main/main.cpp:5:3: note: Calling 'describe'
  bandit::describe("our first test", [](){
  ^
bandit/bandit/grammar.h:33:26: note: Calling 'registered_listener'
    describe(desc, func, detail::registered_listener(), detail::context_stack());
                         ^
bandit/bandit/reporters/reporters.h:17:5: note: 'reporter_' initialized to a null pointer value
    static struct listener* reporter_;
    ^
bandit/bandit/reporters/reporters.h:19:5: note: Taking false branch
    if(reporter)
    ^
bandit/bandit/reporters/reporters.h:24:5: note: Returning null reference
    return *reporter_;
    ^
=======